name: release

on:
  push
  # tags:
  #   - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build-win-mac:
    name: build (${{ matrix.config.name }}, ${{ matrix.config.arch }})
    runs-on:
      ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - name: darwin
            os: macos-latest
            os-cmake-args: '-DCMAKE_CXX_FLAGS="-static-libgcc -static-libstdc++ -flto" -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 ${POSIX_CMAKE_ARGS}'
            build-args: '-j$(sysctl -n hw.ncpu)'
            # bindir: '/build/bin' # check if useful
            arch: amd64
          # - name: windows # TODO still to test
          #   os: windows-latest
          #   arch: 386
          #   extension: .exe
          - name: windows
            os: windows-latest
            os-cmake-args: '-Thost=x64 -DCMAKE_CXX_FLAGS="/MP /std:c++14" -DLLVM_USE_CRT_MINSIZEREL="MT"'
            build-args: '--config MinSizeRel'
            # bindir: '/build/MinSizeRel/bin' # check if useful
            arch: amd64
            extra-tar-args: '--exclude=${RELEASE}/clang/test/Driver/Inputs/* --exclude=${RELEASE}/libcxx/test/std/input.output/filesystems/Inputs/static_test_env/* --exclude=${RELEASE}/libclc/amdgcn-mesa3d'
            extension: .exe
    env:
      COMMON_CMAKE_ARGS: '-DBUILD_SHARED_LIBS=OFF -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra"'
      POSIX_CMAKE_ARGS: '-DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_C_COMPILER=gcc-10'
      RELEASE: 'llvm-project-12.0.0.src'
    defaults:
      run:
        shell: bash
    steps:
    - name: get llvm-project
      run: curl -L https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.0/${RELEASE}.tar.xz | tar -xJ ${{ matrix.config.extra-tar-args }}

    - name: cmake
      run: | 
        cd ${RELEASE}
        mkdir build
        cd build
        cmake ../llvm ${{ env.COMMON_CMAKE_ARGS }} ${{ matrix.config.os-cmake-args }}

    - name: build
      run: cmake --build ${RELEASE}/build ${{ matrix.config.build-args }} --target clang-format clangd

    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: clang-tools-${{ matrix.config.name }}-${{ matrix.config.arch }}
        path: bin/clang*

  build-linux:
    name: build (${{ matrix.config.name }}, ${{ matrix.config.arch }})
    runs-on:
      ubuntu-latest
    # apparently env vars cannot be defined here with container (https://github.community/t/how-to-use-env-with-container-image/17252)
    strategy:
      matrix:
        config:
          - name: linux
            arch: amd64
            os-cmake-args: '-DCMAKE_CXX_COMPILER=x86_64-ubuntu16.04-linux-gnu-g++ -DCMAKE_C_COMPILER=x86_64-ubuntu16.04-linux-gnu-gcc'
          - name: linux
            arch: 386
            os-cmake-args: '-DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_COMPILER=i686-ubuntu16.04-linux-gnu-g++ -DCMAKE_C_COMPILER=i686-ubuntu16.04-linux-gnu-gcc'
          - name: linux
            arch: arm
            os-cmake-args: '-DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++ -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc -DCMAKE_CROSSCOMPILING=True -DLLVM_DEFAULT_TARGET_TRIPLE=arm-linux-gnueabihf -DLLVM_TARGET_ARCH=ARM -DLLVM_TARGETS_TO_BUILD=ARM -DLLVM_TABLEGEN=/tmp/llvm-tblgen -DCLANG_TABLEGEN=/tmp/clang-tblgen'
          - name: linux
            arch: arm64
            os-cmake-args: '-DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_CROSSCOMPILING=True -DLLVM_TARGET_ARCH=AArch64 -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=AArch64 -DLLVM_TABLEGEN=/tmp/llvm-tblgen -DCLANG_TABLEGEN=/tmp/clang-tblgen'

    container:
      image: ghcr.io/arduino/crossbuild:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.CLANG_CI_PAT }}

    steps:

    - name: Set RELEASE vars
      run: echo 'RELEASE=llvm-project-12.0.0.src' >> $GITHUB_ENV

    - name: Set COMMON_CMAKE_ARGS var
      run: echo 'COMMON_CMAKE_ARGS=-DBUILD_SHARED_LIBS=OFF -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" -DCMAKE_CXX_FLAGS="-s -static-libstdc++ -static-libgcc" -DCMAKE_BUILD_TYPE=MinSizeRel' >> $GITHUB_ENV

    - name: get llvm-project
      run: curl -L https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.0/${RELEASE}.tar.xz | tar -xJ

    - name: install Ninja
      run: apt update && apt install ninja-build

    - name: build llvm-tblgen clang-tblgen with the host toolchain
      run: |
        cd ${RELEASE}
        mkdir -p build
        cd build
        cmake -G Ninja ../llvm  ${COMMON_CMAKE_ARGS} -DCMAKE_CXX_COMPILER=x86_64-ubuntu16.04-linux-gnu-g++ -DCMAKE_C_COMPILER=x86_64-ubuntu16.04-linux-gnu-gcc
        ninja llvm-tblgen clang-tblgen
        cp -v bin/llvm-tblgen /tmp
        cp -v bin/clang-tblgen /tmp
        rm -rf *
      if: matrix.config.arch == 'arm' || matrix.config.arch == 'arm64'

    - name: build clangd and clang-format
      run: |
        cd ${RELEASE}
        mkdir -p build
        cd build
        cmake -G Ninja ../llvm ${COMMON_CMAKE_ARGS}  ${{ matrix.config.os-cmake-args }}
        ninja clang-format clangd

    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: clang-tools-${{ matrix.config.name }}-${{ matrix.config.arch }}
        path: |
          ${RELEASE}/build/bin/clangd*
          ${RELEASE}/build/bin/clang-format*
