name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:

  get-version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-tag.outputs.TAG}}
      llvm-version: ${{ steps.get-version.outputs.LLVM_VERSION}}
    steps:
      - id: get-tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
      - id: get-version
        run: echo ::set-output name=LLVM_VERSION::llvm-project-${GITHUB_REF/refs\/tags\//}.src

  build-win-mac:
    needs: get-version
    name: build (${{ matrix.config.name }}, ${{ matrix.config.arch }})
    runs-on:
      ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - name: darwin
            os: macos-latest
            os-cmake-args: '-DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang'
            build-args: '-j$(sysctl -n hw.ncpu)'
            bindir: '/build/bin'
            arch: amd64
          - name: windows
            os: windows-latest
            os-cmake-args: '-DCMAKE_CXX_FLAGS="/MP /std:c++14" -DLLVM_USE_CRT_MINSIZEREL="MT"'
            build-args: '--config MinSizeRel'
            bindir: '/build/MinSizeRel/bin'
            extra-tar-args: '--exclude=${{ needs.get-version.outputs.llvm-version }}/clang/test/Driver/Inputs/* --exclude=${{ needs.get-version.outputs.llvm-version }}/libcxx/test/std/input.output/filesystems/Inputs/static_test_env/* --exclude=${{ needs.get-version.outputs.llvm-version }}/libclc/amdgcn-mesa3d'
            arch: 386
            extension: .exe
          - name: windows
            os: windows-latest
            os-cmake-args: '-Thost=x64 -DCMAKE_CXX_FLAGS="/MP /std:c++14" -DLLVM_USE_CRT_MINSIZEREL="MT"'
            build-args: '--config MinSizeRel'
            bindir: '/build/MinSizeRel/bin'
            arch: amd64
            extra-tar-args: '--exclude=${{ needs.get-version.outputs.llvm-version }}/clang/test/Driver/Inputs/* --exclude=${{ needs.get-version.outputs.llvm-version }}/libcxx/test/std/input.output/filesystems/Inputs/static_test_env/* --exclude=${{ needs.get-version.outputs.llvm-version }}/libclc/amdgcn-mesa3d'
            extension: .exe
    env:
      COMMON_CMAKE_ARGS: '-DBUILD_SHARED_LIBS=OFF -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra"'
    defaults:
      run:
        shell: bash

    steps:
    - name: get llvm-project
      run: curl -L https://github.com/llvm/llvm-project/releases/download/llvmorg-${{ needs.get-version.outputs.tag }}/${{ needs.get-version.outputs.llvm-version }}.tar.xz | tar -xJ ${{ matrix.config.extra-tar-args }}

    - name: cmake
      run: |
        cd ${{ needs.get-version.outputs.llvm-version }}
        mkdir build
        cd build
        cmake ../llvm ${{ env.COMMON_CMAKE_ARGS }} ${{ matrix.config.os-cmake-args }}

    - name: build
      run: cmake --build ${{ needs.get-version.outputs.llvm-version }}/build ${{ matrix.config.build-args }} --target clang-format clangd

    - name: print macos dependencies
      run:  |
        otool -L ${{ needs.get-version.outputs.llvm-version }}${{ matrix.config.bindir }}/clangd
        otool -L ${{ needs.get-version.outputs.llvm-version }}${{ matrix.config.bindir }}/clang-format
      if: matrix.config.os == 'macos-latest'

    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: clang_${{ matrix.config.name }}_${{ matrix.config.arch }}
        path: |
          ${{ needs.get-version.outputs.llvm-version }}${{ matrix.config.bindir }}/clangd${{ matrix.config.extension }}
          ${{ needs.get-version.outputs.llvm-version }}${{ matrix.config.bindir }}/clang-format${{ matrix.config.extension }}

  build-linux:
    needs: get-version
    name: build (${{ matrix.config.name }}, ${{ matrix.config.arch }})
    runs-on:
      ubuntu-latest
    # apparently env vars cannot be defined here with container (https://github.community/t/how-to-use-env-with-container-image/17252)
    strategy:
      matrix:
        config:
          - name: linux
            arch: amd64
            os-cmake-args: '-DCMAKE_CXX_COMPILER=x86_64-ubuntu16.04-linux-gnu-g++ -DCMAKE_C_COMPILER=x86_64-ubuntu16.04-linux-gnu-gcc'
          - name: linux
            arch: 386
            os-cmake-args: '-DCMAKE_CXX_COMPILER=i686-ubuntu16.04-linux-gnu-g++ -DCMAKE_C_COMPILER=i686-ubuntu16.04-linux-gnu-gcc'
          - name: linux
            arch: arm
            os-cmake-args: '-DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++ -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc -DCMAKE_CROSSCOMPILING=True -DLLVM_DEFAULT_TARGET_TRIPLE=arm-linux-gnueabihf -DLLVM_TARGET_ARCH=ARM -DLLVM_TARGETS_TO_BUILD=ARM -DLLVM_TABLEGEN=/tmp/llvm-tblgen -DCLANG_TABLEGEN=/tmp/clang-tblgen'
          - name: linux
            arch: arm64
            os-cmake-args: '-DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_CROSSCOMPILING=True -DLLVM_TARGET_ARCH=AArch64 -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=AArch64 -DLLVM_TABLEGEN=/tmp/llvm-tblgen -DCLANG_TABLEGEN=/tmp/clang-tblgen'

    container:
      image: ghcr.io/arduino/crossbuild:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.CLANG_CI_PAT }}

    steps:
    - name: Set env vars
      run: echo "COMMON_CMAKE_ARGS=-DBUILD_SHARED_LIBS=OFF -DLLVM_ENABLE_PROJECTS=\"clang;clang-tools-extra\" -DCMAKE_CXX_FLAGS=\"-s -static-libstdc++ -static-libgcc\" -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_SYSTEM_NAME=\"Linux\"" >> $GITHUB_ENV

    - name: get llvm-project
      run: curl -L https://github.com/llvm/llvm-project/releases/download/llvmorg-${{ needs.get-version.outputs.tag }}/${{ needs.get-version.outputs.llvm-version }}.tar.xz | tar -xJ

    - name: install Ninja
      run: apt update && apt install ninja-build

    - name: build llvm-tblgen clang-tblgen with the host toolchain
      run: |
        cd ${{ needs.get-version.outputs.llvm-version }}
        mkdir -p build
        cd build
        cmake -G Ninja ../llvm  ${{ env.COMMON_CMAKE_ARGS }} -DCMAKE_CXX_COMPILER=x86_64-ubuntu16.04-linux-gnu-g++ -DCMAKE_C_COMPILER=x86_64-ubuntu16.04-linux-gnu-gcc
        ninja llvm-tblgen clang-tblgen
        cp -v bin/llvm-tblgen /tmp
        cp -v bin/clang-tblgen /tmp
        rm -rf *
      if: matrix.config.arch == 'arm' || matrix.config.arch == 'arm64'

    - name: build clangd and clang-format
      run: |
        cd ${{ needs.get-version.outputs.llvm-version }}
        mkdir -p build
        cd build
        cmake -G Ninja ../llvm ${{ env.COMMON_CMAKE_ARGS }}  ${{ matrix.config.os-cmake-args }}
        ninja clang-format clangd

    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: clang_${{ matrix.config.name }}_${{ matrix.config.arch }}
        path: |
          ${{ needs.get-version.outputs.llvm-version }}/build/bin/clangd*
          ${{ needs.get-version.outputs.llvm-version }}/build/bin/clang-format*

  create-release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-win-mac, get-version]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2

      - name: Prepare artifacts for the release
        run: |
          mkdir release
          declare -a target_folders=("linux_amd64" "linux_386" "linux_arm64" "linux_arm" "darwin_amd64" "windows_386" "windows_amd64")
          for folder in "${target_folders[@]}"
          do
            chmod -v +x clang_$folder/*
            FILENAME=clang-${{ needs.get-version.outputs.tag }}-${folder}.tar.bz2
            tar -cvjf $FILENAME clang_$folder/
          done
          mv -v clang*.tar.bz2 release/

      - name: Create Github Release and upload artifacts
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          # NOTE: "Artifact is a directory" warnings are expected and don't indicate a problem
          # (all the files we need are in the release folder root)
          artifacts: release/*
